#
# cmake/_Headers.cmake is generated by `mulle-sde`. Edits will be lost.
#
if( MULLE_TRACE_INCLUDE)
   MESSAGE( STATUS "# Include \"${CMAKE_CURRENT_LIST_FILE}\"" )
endif()

set( PRIVATE_HEADERS
import-private.h
)

set( PUBLIC_HEADERS
MulleObjCLoader+MulleObjCOSWindowsFoundation.h
MulleObjCOSWindowsFoundation.h
NSCondition.h
import.h
)

