/*
*   This file will be regenerated by `mulle-sde update` and any edits will be
*   lost. Suppress generation of this file with:
*      mulle-sde environment --global *         set MULLE_SOURCETREE_TO_C_IMPORT_FILE DISABLE
*
*   To not generate any header files:
*      mulle-sde environment --global *         set MULLE_SOURCETREE_TO_C_RUN DISABLE
*/

#ifndef _mulle_objc_free_bsd_foundation_import_h__
#define _mulle_objc_free_bsd_foundation_import_h__

#include "_MulleObjCFreeBSDFoundation-include.h"

// remove with `mulle-sourcetree mark MulleObjCPosixFoundation no-header`
// rename with `mulle-sourcetree mark MulleObjCPosixFoundation set include whatever.h`
# import <MulleObjCPosixFoundation/MulleObjCPosixFoundation.h>   // MulleObjCPosixFoundation

#endif
