#
# cmake/_Headers.cmake is generated by `mulle-sde`. Edits will be lost.
#
if( MULLE_TRACE_INCLUDE)
   MESSAGE( STATUS "# Include \"${CMAKE_CURRENT_LIST_FILE}\"" )
endif()

set( INCLUDE_DIRS
.
Categories
Functions
)

set( PRIVATE_HEADERS
Categories/NSArray+OSBase-Private.h
Categories/NSDate+OSBase-Private.h
Categories/NSDictionary+OSBase-Private.h
Functions/NSPageAllocation-Private.h
NSBundle-Private.h
NSFileManager-Private.h
NSPathUtilities+OSBase-Private.h
NSRunLoop-Private.h
NSTask-Private.h
import-private.h
include-private.h
)

set( PUBLIC_HEADERS
Categories/NSArchiver+OSBase.h
Categories/NSArray+OSBase.h
Categories/NSCalendarDate+NSUserDefaults.h
Categories/NSData+OSBase.h
Categories/NSDictionary+OSBase.h
Categories/NSString+CString.h
Categories/NSString+OSBase.h
Categories/NSTask+System.h
Categories/NSURL+OSBase.h
Functions/NSLog.h
Functions/NSPageAllocation.h
Functions/NSPathUtilities.h
MulleObjCOSBaseFoundation.h
NSBundle.h
NSConditionLock.h
NSDirectoryEnumerator.h
NSFileHandle+NSRunLoop.h
NSFileHandle.h
NSFileManager.h
NSPipe.h
NSProcessInfo.h
NSRunLoop.h
NSTask.h
NSUserDefaults.h
import.h
include.h
)

