# cmake/_Libraries.cmake is generated by `mulle-sde`. Edits will be lost.
#
if( MULLE_TRACE_INCLUDE)
   message( STATUS "# Include \"${CMAKE_CURRENT_LIST_FILE}\"" )
endif()

if( NOT MULLEOBJCOSBASEFOUNDATION_LIBRARY)
   find_library( MULLEOBJCOSBASEFOUNDATION_LIBRARY NAMES MulleObjCOSBaseFoundation)
   message( STATUS "MULLEOBJCOSBASEFOUNDATION_LIBRARY is ${MULLEOBJCOSBASEFOUNDATION_LIBRARY}")

   # the order looks ascending, but due to the way this file is read
   # it ends up being descending, which is what we need
   if( MULLEOBJCOSBASEFOUNDATION_LIBRARY)
      set( OS_SPECIFIC_LIBRARIES
         ${OS_SPECIFIC_LIBRARIES}
         ${MULLEOBJCOSBASEFOUNDATION_LIBRARY}
         CACHE INTERNAL "need to cache this"
      )
      # temporarily expand CMAKE_MODULE_PATH
      get_filename_component( _TMP_MULLEOBJCOSBASEFOUNDATION_ROOT "${MULLEOBJCOSBASEFOUNDATION_LIBRARY}" DIRECTORY)
      get_filename_component( _TMP_MULLEOBJCOSBASEFOUNDATION_ROOT "${_TMP_MULLEOBJCOSBASEFOUNDATION_ROOT}" DIRECTORY)

      # search for DependenciesAndLibraries.cmake to include
      foreach( _TMP_MULLEOBJCOSBASEFOUNDATION_NAME in MulleObjCOSBaseFoundation)
         set( _TMP_MULLEOBJCOSBASEFOUNDATION_DIR "${_TMP_MULLEOBJCOSBASEFOUNDATION_ROOT}/include/${_TMP_MULLEOBJCOSBASEFOUNDATION_NAME}/cmake")
         # use explicit path to avoid "surprises"
         if( EXISTS "${_TMP_MULLEOBJCOSBASEFOUNDATION_DIR}/DependenciesAndLibraries.cmake")
            unset( MULLEOBJCOSBASEFOUNDATION_DEFINITIONS)
            list( INSERT CMAKE_MODULE_PATH 0 "${_TMP_MULLEOBJCOSBASEFOUNDATION_DIR}")
            include( "${_TMP_MULLEOBJCOSBASEFOUNDATION_DIR}/DependenciesAndLibraries.cmake")
            list( REMOVE_ITEM CMAKE_MODULE_PATH "${_TMP_MULLEOBJCOSBASEFOUNDATION_DIR}")
            set( INHERITED_DEFINITIONS
               ${INHERITED_DEFINITIONS}
               ${MULLEOBJCOSBASEFOUNDATION_DEFINITIONS}
               CACHE INTERNAL "need to cache this"
            )
            break()
         endif()
      endforeach()
   else()
      message( FATAL_ERROR "MULLEOBJCOSBASEFOUNDATION_LIBRARY was not found")
   endif()
endif()
