# cmake/_Sources.cmake is generated by `mulle-sde`. Edits will be lost.
#
if( MULLE_TRACE_INCLUDE)
   MESSAGE( STATUS "# Include \"${CMAKE_CURRENT_LIST_FILE}\"" )
endif()

set( SOURCES
Locale.m
NSCalendarDate+Localization.m
)

set( STANDALONE_SOURCES
Locale-standalone.m
src/Locale-standalone.m
)
