#
# cmake/_Libraries.cmake is generated by `mulle-sde`. Edits will be lost.
# Disable generation of this file with:
#   mulle-sde environment  --global set MULLE_SOURCETREE_TO_CMAKE_LIBRARIES_FILE DISABLE

if( MULLE_TRACE_INCLUDE)
   message( STATUS "# Include \"${CMAKE_CURRENT_LIST_FILE}\"" )
endif()

#
# Generated from sourcetree: MulleObjCPosixFoundation;no-cmakeinherit,no-link;
# Disable with: `mulle-sourcetree mark MulleObjCPosixFoundation no-link`
#
if( NOT MULLE_OBJC_POSIX_FOUNDATION_HEADER)
   find_file( MULLE_OBJC_POSIX_FOUNDATION_HEADER NAMES MulleObjCPosixFoundation/MulleObjCPosixFoundation.h MulleObjCPosixFoundation.h)
   message( STATUS "MULLE_OBJC_POSIX_FOUNDATION_HEADER is ${MULLE_OBJC_POSIX_FOUNDATION_HEADER}")

   #
   # Add to list of header files.
   # Disable with: `mulle-sourcetree mark MulleObjCPosixFoundation no-cmakeadd`
   #
   set( ALL_LOAD_HEADER_ONLY_LIBRARIES
      ${MULLE_OBJC_POSIX_FOUNDATION_HEADER}
      ${ALL_LOAD_HEADER_ONLY_LIBRARIES}
      CACHE INTERNAL "need to cache this"
   )
   if( MULLE_OBJC_POSIX_FOUNDATION_HEADER)
      # intentionally left blank
   else()
      message( FATAL_ERROR "MULLE_OBJC_POSIX_FOUNDATION_HEADER was not found")
   endif()
endif()
