#
# cmake/_Sources.cmake is generated by `mulle-sde`. Edits will be lost.
#
if( MULLE_TRACE_INCLUDE)
   MESSAGE( STATUS "# Include \"${CMAKE_CURRENT_LIST_FILE}\"" )
endif()

set( SOURCES
NSBundle+Linux.m
NSCalendarDate+Linux.m
NSDateFormatter+Linux.m
NSFileManager+Linux.m
_NSGMTTimeZone+Linux.m
NSLocale+Linux.m
NSPathUtilities+Linux.m
NSProcessInfo+Linux.m
NSString+Linux.m
NSTask+Linux.m
NSTimeZone+Linux.m
)

set( STAGE2_SOURCES
MulleObjCLoader+MulleObjCLinuxFoundation.m
)
