/*
   This file will be regenerated by `mulle-sde update|monitor`.
   Edits will be lost.
*/

#ifndef _mulleobjcposixfoundation__dependencies_h__
#define _mulleobjcposixfoundation__dependencies_h__

# include <MulleObjCOSBaseFoundation/MulleObjCOSBaseFoundation.h>   // MulleObjCOSBaseFoundation

#endif
