      { @selector( MulleObjCLoader), @selector( MulleObjCOSBaseFoundation) },      // 47a9beb6;MulleObjCLoader;bc81d222;MulleObjCOSBaseFoundation
      { @selector( NSBundle), @selector( Posix) },      // c2f95c66;NSBundle;ae1faa81;Posix
      { @selector( NSCalendarDate), @selector( Posix) },      // b8742fcb;NSCalendarDate;ae1faa81;Posix
      { @selector( NSCondition), MULLE_OBJC_NO_CATEGORYID },      // 0397143e;NSCondition;;
      { @selector( NSData), @selector( Posix) },      // 8fce7861;NSData;ae1faa81;Posix
      { @selector( NSDate), @selector( Posix) },      // cfcedd21;NSDate;ae1faa81;Posix
      { @selector( NSDirectoryEnumerator), @selector( Posix) },      // c1158d70;NSDirectoryEnumerator;ae1faa81;Posix
      { @selector( NSFileHandle), @selector( Posix) },      // 01a8a865;NSFileHandle;ae1faa81;Posix
      { @selector( NSFileManager), @selector( Posix) },      // 56d57ffc;NSFileManager;ae1faa81;Posix
      { @selector( NSLocale), @selector( Posix) },      // 22b7d78c;NSLocale;ae1faa81;Posix
      { @selector( NSPipe), @selector( Posix) },      // 09f46823;NSPipe;ae1faa81;Posix
      { @selector( NSProcessInfo), @selector( Posix) },      // 208b1df5;NSProcessInfo;ae1faa81;Posix
      { @selector( NSRunLoop), @selector( Posix) },      // e3bb595b;NSRunLoop;ae1faa81;Posix
      { @selector( NSTask), @selector( Posix) },      // 90ec29ba;NSTask;ae1faa81;Posix
      { @selector( NSTimeZone), @selector( Posix) },      // 190d1ade;NSTimeZone;ae1faa81;Posix
      { @selector( _NSPosixDateFormatter), MULLE_OBJC_NO_CATEGORYID },      // 316287e6;_NSPosixDateFormatter;;
