      { @selector( MulleObjCLoader), @selector( MulleObjCOSBaseFoundation) },      // 58bd58d3;MulleObjCLoader;8aabd7dc;MulleObjCOSBaseFoundation
      { @selector( NSBundle), @selector( Posix) },      // 301a6dd8;NSBundle;1ac23aba;Posix
      { @selector( NSCalendarDate), @selector( Posix) },      // 732630c6;NSCalendarDate;1ac23aba;Posix
      { @selector( NSCondition), MULLE_OBJC_NO_CATEGORYID },      // 3ce070c7;NSCondition;;
      { @selector( NSData), @selector( Posix) },      // 7d1455e8;NSData;1ac23aba;Posix
      { @selector( NSDate), @selector( Posix) },      // 7d1455ec;NSDate;1ac23aba;Posix
      { @selector( NSDirectoryEnumerator), @selector( Posix) },      // 4609f60f;NSDirectoryEnumerator;1ac23aba;Posix
      { @selector( NSFileHandle), @selector( Posix) },      // e82be8e0;NSFileHandle;1ac23aba;Posix
      { @selector( NSFileManager), @selector( Posix) },      // be98ed67;NSFileManager;1ac23aba;Posix
      { @selector( NSLocale), @selector( Posix) },      // 60293bce;NSLocale;1ac23aba;Posix
      { @selector( NSPipe), @selector( Posix) },      // 06832e24;NSPipe;1ac23aba;Posix
      { @selector( NSProcessInfo), @selector( Posix) },      // f87f34cf;NSProcessInfo;1ac23aba;Posix
      { @selector( NSRunLoop), @selector( Posix) },      // 68c55409;NSRunLoop;1ac23aba;Posix
      { @selector( NSTask), @selector( Posix) },      // b04725e7;NSTask;1ac23aba;Posix
      { @selector( NSTimeZone), @selector( Posix) },      // 4bf7bd11;NSTimeZone;1ac23aba;Posix
      { @selector( _NSPosixDateFormatter), MULLE_OBJC_NO_CATEGORYID },      // 963fbdc8;_NSPosixDateFormatter;;
