# cmake/_Headers.cmake is generated by `mulle-sde`. Edits will be lost.
#
if( MULLE_TRACE_INCLUDE)
   MESSAGE( STATUS "# Include \"${CMAKE_CURRENT_LIST_FILE}\"" )
endif()

 

set( PUBLIC_HEADERS
dependencies.h
dependencies.inc
mulle_bsd_tm.h
) 

