/*
* This file will be regenerated by `mulle-sde update|monitor`.
* Edits will be lost.
* Suppress this file with MULLE_SDE_IMPORT_FILENAME NONE|DISABLE.
*/

#ifndef _mulle_objc_linux_foundation_import_h__
#define _mulle_objc_linux_foundation_import_h__

# import <MulleObjCPosixFoundation/MulleObjCPosixFoundation.h>   // MulleObjCPosixFoundation

#endif
