/*
*   This file will be regenerated by `mulle-sde update` and any edits will be
*   lost. Suppress generation of this file with:
*      mulle-sde environment --global \
*         set MULLE_SOURCETREE_TO_C_IMPORT_FILE DISABLE
*
*   To not generate any header files:
*      mulle-sde environment --global \
*         set MULLE_SOURCETREE_TO_C_RUN DISABLE
*/

#ifndef _mulle_objc_linux_foundation_import_h__
#define _mulle_objc_linux_foundation_import_h__

// How to tweak the following MulleObjCPosixFoundation #import
//    remove:          `mulle-sourcetree mark MulleObjCPosixFoundation no-header`
//    rename:          `mulle-sourcetree mark MulleObjCPosixFoundation set include whatever.h`
//    toggle public:   `mulle-sourcetree mark MulleObjCPosixFoundation [no-]public`
//    toggle optional: `mulle-sourcetree mark MulleObjCPosixFoundation [no-]require`
//    remove for os:   `mulle-sourcetree mark MulleObjCPosixFoundation no-os-<osname>`
# import <MulleObjCPosixFoundation/MulleObjCPosixFoundation.h>   // MulleObjCPosixFoundation

#include "_MulleObjCLinuxFoundation-include.h"


#endif
