/*
 *   This file will be regenerated by `mulle-sourcetree-to-c` via
 *   `mulle-sde reflect` and any edits will be lost.
 *   Suppress generation of this file with:
 *
 *      mulle-sde environment set MULLE_SOURCETREE_TO_C_IMPORT_FILE DISABLE
 *
 *   To not let mulle-sourcetree-to-c generate any header files:
 *
 *      mulle-sde environment set MULLE_SOURCETREE_TO_C_RUN DISABLE
 *
 */

// You can tweak the following #import with these commands.
// (Use 699EE9F6-53EE-4D2C-B2EC-7F5047DEC6C7 instead of MulleObjCInetFoundation if there are duplicate entries)
//    remove:             `mulle-sde dependency mark MulleObjCInetFoundation no-header`
//    rename:             `mulle-sde dependency|library set MulleObjCInetFoundation include whatever.h`
//    reorder:            `mulle-sde dependency move MulleObjCInetFoundation <up|down>`
//    toggle #import:     `mulle-sde dependency mark MulleObjCInetFoundation [no-]import`
//    toggle public:      `mulle-sde dependency mark MulleObjCInetFoundation [no-]public`
//    toggle optional:    `mulle-sde dependency mark MulleObjCInetFoundation [no-]require`
//    remove for platform:`mulle-sde dependency mark MulleObjCInetFoundation no-platform-<uname>`
//        (use `mulle-sourcetree-to-c --unames` to list known values)
#import <MulleObjCInetFoundation/MulleObjCInetFoundation.h>   // MulleObjCInetFoundation

// You can tweak the following #import with these commands.
// (Use FAC0484F-7450-4A14-9C8F-5AC7BB05879B instead of MulleObjCOSFoundation if there are duplicate entries)
//    remove:             `mulle-sde dependency mark MulleObjCOSFoundation no-header`
//    rename:             `mulle-sde dependency|library set MulleObjCOSFoundation include whatever.h`
//    reorder:            `mulle-sde dependency move MulleObjCOSFoundation <up|down>`
//    toggle #import:     `mulle-sde dependency mark MulleObjCOSFoundation [no-]import`
//    toggle public:      `mulle-sde dependency mark MulleObjCOSFoundation [no-]public`
//    toggle optional:    `mulle-sde dependency mark MulleObjCOSFoundation [no-]require`
//    remove for platform:`mulle-sde dependency mark MulleObjCOSFoundation no-platform-<uname>`
//        (use `mulle-sourcetree-to-c --unames` to list known values)
#import <MulleObjCOSFoundation/MulleObjCOSFoundation.h>   // MulleObjCOSFoundation

#ifdef __has_include
# if __has_include( "_MulleObjCInetOSFoundation-include.h")
#  include "_MulleObjCInetOSFoundation-include.h"
# endif
#endif

