      { @selector( MulleObjCLoader), @selector( MulleFoundationBase) },      // 47a9beb6;MulleObjCLoader;efab19ea;MulleFoundationBase
      { @selector( MulleObjCLoader), @selector( MulleObjCInetFoundation) },      // 47a9beb6;MulleObjCLoader;088ec1b3;MulleObjCInetFoundation
      { @selector( MulleObjCLoader), @selector( MulleObjCOSFoundation) },      // 47a9beb6;MulleObjCLoader;94ffe970;MulleObjCOSFoundation
      { @selector( NSData), @selector( NSURL) },      // 8fce7861;NSData;6b1e8f73;NSURL
      { @selector( NSHost), @selector( OS) },      // fe455508;NSHost;de4ab977;OS
      { @selector( NSURL), @selector( Filesystem) },      // 6b1e8f73;NSURL;73db5ea2;Filesystem
