      { @selector( MulleObjCDeps), @selector( MulleObjCInetFoundation) },      // 3c20656f;MulleObjCDeps;088ec1b3;MulleObjCInetFoundation
      { @selector( MulleObjCDeps), @selector( MulleObjCOSFoundation) },      // 3c20656f;MulleObjCDeps;94ffe970;MulleObjCOSFoundation
      { @selector( NSData), @selector( NSURL) },      // 8fce7861;NSData;6b1e8f73;NSURL
      { @selector( NSHost), @selector( OS) },      // fe455508;NSHost;de4ab977;OS
      { @selector( NSURL), @selector( Filesystem) },      // 6b1e8f73;NSURL;73db5ea2;Filesystem
