/*
*   This file will be regenerated by `mulle-sde update` and any edits will be
*   lost. Suppress generation of this file with:
*      mulle-sde environment --global \
*         set MULLE_SOURCETREE_TO_C_IMPORT_FILE DISABLE
*
*   To not generate any header files:
*      mulle-sde environment --global \
*         set MULLE_SOURCETREE_TO_C_RUN DISABLE
*/

#ifndef _mulle_objc_os_windows_foundation_import_h__
#define _mulle_objc_os_windows_foundation_import_h__

// How to tweak the following MulleObjCOSBaseFoundation #import
//    remove:        `mulle-sourcetree mark MulleObjCOSBaseFoundation no-header`
//    rename:        `mulle-sourcetree mark MulleObjCOSBaseFoundation set include whatever.h`
//    make private:  `mulle-sourcetree mark MulleObjCOSBaseFoundation no-public`
//    make public:   `mulle-sourcetree mark MulleObjCOSBaseFoundation public`
//    make optional: `mulle-sourcetree mark MulleObjCOSBaseFoundation no-require`
//    remove for os: `mulle-sourcetree mark MulleObjCOSBaseFoundation no-os-<osname>`
# import <MulleObjCOSBaseFoundation/MulleObjCOSBaseFoundation.h>   // MulleObjCOSBaseFoundation

#include "_MulleObjCOSWindowsFoundation-include.h"


#endif
