/*
   This file will be regenerated by `mulle-sde update|monitor`.
   Edits will be lost.
*/

#ifndef _mulleobjcbsdfoundation__dependencies_h__
#define _mulleobjcbsdfoundation__dependencies_h__

# include <MulleObjCPosixFoundation/MulleObjCPosixFoundation.h>   // MulleObjCPosixFoundation

#endif
