      { @selector( MulleObjCLoader), @selector( MulleObjCPosixFoundation) },      // 58bd58d3;MulleObjCLoader;bf9cc404;MulleObjCPosixFoundation
      { @selector( NSCalendarDate), @selector( BSD) },      // 732630c6;NSCalendarDate;4c4a4c98;BSD
      { @selector( NSDateFormatter), @selector( BSD) },      // baad3d86;NSDateFormatter;4c4a4c98;BSD
      { @selector( NSLocale), @selector( BSD) },      // 60293bce;NSLocale;4c4a4c98;BSD
      { @selector( NSProcessInfo), @selector( BSD) },      // f87f34cf;NSProcessInfo;4c4a4c98;BSD
      { @selector( NSTask), @selector( BSD) },      // b04725e7;NSTask;4c4a4c98;BSD
      { @selector( NSTimeZone), @selector( BSD) },      // 4bf7bd11;NSTimeZone;4c4a4c98;BSD
      { @selector( _NSGMTTimeZone), @selector( BSD) },      // 50cec3ce;_NSGMTTimeZone;4c4a4c98;BSD
