      { @selector( NSCalendarDate), @selector( BSD) },      // b8742fcb;NSCalendarDate;999e852d;BSD
      { @selector( NSDateFormatter), @selector( BSD) },      // 6d2cd542;NSDateFormatter;999e852d;BSD
      { @selector( NSLocale), @selector( BSD) },      // 22b7d78c;NSLocale;999e852d;BSD
      { @selector( NSProcessInfo), @selector( BSD) },      // 208b1df5;NSProcessInfo;999e852d;BSD
      { @selector( NSTask), @selector( BSD) },      // 90ec29ba;NSTask;999e852d;BSD
      { @selector( NSTimeZone), @selector( BSD) },      // 190d1ade;NSTimeZone;999e852d;BSD
      { @selector( _NSGMTTimeZone), @selector( BSD) },      // 60527041;_NSGMTTimeZone;999e852d;BSD
