/*
   This file will be regenerated by `mulle-sde update|monitor`.
   Edits will be lost.
*/

#ifndef _mulleobjcosfoundation__dependencies_h__
#define _mulleobjcosfoundation__dependencies_h__

# include <MulleObjCOSBaseFoundation/MulleObjCOSBaseFoundation.h>   // src/Base

# include <MulleObjCPosixFoundation/MulleObjCPosixFoundation.h>   // src/Posix

#endif
