/*
* This file will be regenerated by `mulle-sde update|monitor`.
* Edits will be lost.
* Suppress this file with MULLE_SDE_IMPORT_FILENAME NONE|DISABLE.
*/

#ifndef _mulle_objc_os_foundation_import_h__
#define _mulle_objc_os_foundation_import_h__

# import <MulleObjCOSBaseFoundation/MulleObjCOSBaseFoundation.h>   // src/Base

# import <MulleObjCPosixFoundation/MulleObjCPosixFoundation.h>   // src/Posix

#endif
