/*
   This file will be regenerated by `mulle-sde update|monitor`.
   Edits will be lost. Suppress this file with:

   mulle-sde environment set MULLE_SOURCETREE_TO_C_IMPORT_FILE DISABLE
*/

#ifndef _mulle_objc_os_foundation_import_h__
#define _mulle_objc_os_foundation_import_h__

// library: remove with `mark no-header`, rename with `set include`
# import <MulleObjCOSBaseFoundation/MulleObjCOSBaseFoundation.h>   // src/Base

// library: remove with `mark no-header`, rename with `set include`
# import <MulleObjCPosixFoundation/MulleObjCPosixFoundation.h>   // src/Posix

#endif
