/*
*   This file will be regenerated by `mulle-sde update` and any edits will be
*   lost. Suppress generation of this file with:
*      mulle-sde environment --global \
*         set MULLE_SOURCETREE_TO_C_IMPORT_FILE DISABLE
*
*   To not generate any header files:
*      mulle-sde environment --global \
*         set MULLE_SOURCETREE_TO_C_RUN DISABLE
*/

#ifndef _mulle_objc_inet_os_foundation_import_h__
#define _mulle_objc_inet_os_foundation_import_h__

// How to tweak the following MulleObjCInetFoundation #import
//    remove:          `mulle-sourcetree mark MulleObjCInetFoundation no-header`
//    rename:          `mulle-sourcetree mark MulleObjCInetFoundation set include whatever.h`
//    toggle public:   `mulle-sourcetree mark MulleObjCInetFoundation [no-]public`
//    toggle optional: `mulle-sourcetree mark MulleObjCInetFoundation [no-]require`
//    remove for os:   `mulle-sourcetree mark MulleObjCInetFoundation no-os-<osname>`
# import <MulleObjCInetFoundation/MulleObjCInetFoundation.h>   // MulleObjCInetFoundation

// How to tweak the following MulleObjCOSFoundation #import
//    remove:          `mulle-sourcetree mark MulleObjCOSFoundation no-header`
//    rename:          `mulle-sourcetree mark MulleObjCOSFoundation set include whatever.h`
//    toggle public:   `mulle-sourcetree mark MulleObjCOSFoundation [no-]public`
//    toggle optional: `mulle-sourcetree mark MulleObjCOSFoundation [no-]require`
//    remove for os:   `mulle-sourcetree mark MulleObjCOSFoundation no-os-<osname>`
# import <MulleObjCOSFoundation/MulleObjCOSFoundation.h>   // MulleObjCOSFoundation

#include "_MulleObjCInetOSFoundation-include.h"


#endif
