      { @selector( MulleObjCLoader), @selector( MulleObjCInetFoundation) },      // 58bd58d3,307411f3
      { @selector( MulleObjCLoader), @selector( MulleObjCStandardFoundation) },      // 58bd58d3,efe3d73e
      { @selector( NSArchiver), @selector( OSBase) },      // 3140e86c,ec55440c
      { @selector( NSArray), @selector( OSBasePrivate) },      // 55e6335f,2d902ee5
      { @selector( NSArray), @selector( Posix) },      // 55e6335f,1ac23aba
      { @selector( NSBundle), @selector( Darwin) },      // 301a6dd8,5729b300
      { @selector( NSBundle), @selector( Posix) },      // 301a6dd8,1ac23aba
      { @selector( NSBundle), MULLE_OBJC_NO_CATEGORYID },      // 301a6dd8,00000000
      { @selector( NSCalendarDate), @selector( BSD) },      // 732630c6,4c4a4c98
      { @selector( NSCalendarDate), @selector( NSUserDefaults) },      // 732630c6,0944b917
      { @selector( NSCalendarDate), @selector( Posix) },      // 732630c6,1ac23aba
      { @selector( NSCondition), MULLE_OBJC_NO_CATEGORYID },      // 3ce070c7,00000000
      { @selector( NSConditionLock), MULLE_OBJC_NO_CATEGORYID },      // 340900d6,00000000
      { @selector( NSData), @selector( OSBase) },      // 7d1455e8,ec55440c
      { @selector( NSData), @selector( Posix) },      // 7d1455e8,1ac23aba
      { @selector( NSDate), @selector( NSUserDefaults) },      // 7d1455ec,0944b917
      { @selector( NSDate), @selector( Posix) },      // 7d1455ec,1ac23aba
      { @selector( NSDateFormatter), @selector( BSD) },      // baad3d86,4c4a4c98
      { @selector( NSDictionary), @selector( OSBase) },      // ca46313c,ec55440c
      { @selector( NSDictionary), @selector( OSBasePrivate) },      // ca46313c,2d902ee5
      { @selector( NSDirectoryEnumerator), @selector( Posix) },      // 4609f60f,1ac23aba
      { @selector( NSDirectoryEnumerator), MULLE_OBJC_NO_CATEGORYID },      // 4609f60f,00000000
      { @selector( NSFileHandle), @selector( NSRunLoop) },      // e82be8e0,68c55409
      { @selector( NSFileHandle), @selector( Posix) },      // e82be8e0,1ac23aba
      { @selector( NSFileHandle), @selector( _NSFileDescriptor) },      // e82be8e0,946746f0
      { @selector( NSFileHandle), MULLE_OBJC_NO_CATEGORYID },      // e82be8e0,00000000
      { @selector( NSFileManager), @selector( Darwin) },      // be98ed67,5729b300
      { @selector( NSFileManager), @selector( Posix) },      // be98ed67,1ac23aba
      { @selector( NSFileManager), MULLE_OBJC_NO_CATEGORYID },      // be98ed67,00000000
      { @selector( NSHost), @selector( OSBase) },      // 324806f6,ec55440c
      { @selector( NSLocale), @selector( BSD) },      // 60293bce,4c4a4c98
      { @selector( NSLocale), @selector( Posix) },      // 60293bce,1ac23aba
      { @selector( NSNullDeviceFileHandle), MULLE_OBJC_NO_CATEGORYID },      // 9747f3d1,00000000
      { @selector( NSPipe), @selector( Posix) },      // 06832e24,1ac23aba
      { @selector( NSPipe), MULLE_OBJC_NO_CATEGORYID },      // 06832e24,00000000
      { @selector( NSProcessInfo), @selector( BSD) },      // f87f34cf,4c4a4c98
      { @selector( NSProcessInfo), @selector( Darwin) },      // f87f34cf,5729b300
      { @selector( NSProcessInfo), @selector( Posix) },      // f87f34cf,1ac23aba
      { @selector( NSProcessInfo), MULLE_OBJC_NO_CATEGORYID },      // f87f34cf,00000000
      { @selector( NSRunLoop), @selector( Posix) },      // 68c55409,1ac23aba
      { @selector( NSRunLoop), MULLE_OBJC_NO_CATEGORYID },      // 68c55409,00000000
      { @selector( NSString), @selector( CString) },      // 85e3fa43,6eddb6b7
      { @selector( NSString), @selector( Darwin) },      // 85e3fa43,5729b300
      { @selector( NSString), @selector( OSBase) },      // 85e3fa43,ec55440c
      { @selector( NSTask), @selector( BSD) },      // b04725e7,4c4a4c98
      { @selector( NSTask), @selector( Darwin) },      // b04725e7,5729b300
      { @selector( NSTask), @selector( Posix) },      // b04725e7,1ac23aba
      { @selector( NSTask), @selector( System) },      // b04725e7,8bce35aa
      { @selector( NSTask), MULLE_OBJC_NO_CATEGORYID },      // b04725e7,00000000
      { @selector( NSTimeZone), @selector( Posix) },      // 4bf7bd11,1ac23aba
      { @selector( NSURL), @selector( OSBase) },      // b15f7adb,ec55440c
      { @selector( NSUserDefaults), @selector( Conveniences) },      // 0944b917,7fd11f11
      { @selector( NSUserDefaults), MULLE_OBJC_NO_CATEGORYID },      // 0944b917,00000000
      { @selector( _NSGMTTimeZone), @selector( BSD) },      // 50cec3ce,4c4a4c98
      { @selector( _NSPosixDateFormatter), MULLE_OBJC_NO_CATEGORYID },      // 963fbdc8,00000000
