      { @selector( MulleObjCLoader), @selector( MulleObjCLinuxFoundation) },      // 47a9beb6;MulleObjCLoader;31a78b3f;MulleObjCLinuxFoundation
      { @selector( MulleObjCLoader), @selector( MulleObjCOSBaseFoundation) },      // 47a9beb6;MulleObjCLoader;bc81d222;MulleObjCOSBaseFoundation
      { @selector( MulleObjCLoader), @selector( MulleObjCPosixFoundation) },      // 47a9beb6;MulleObjCLoader;66ba74e2;MulleObjCPosixFoundation
