#
# cmake/_Headers.cmake is generated by `mulle-sde`. Edits will be lost.
#
if( MULLE_TRACE_INCLUDE)
   MESSAGE( STATUS "# Include \"${CMAKE_CURRENT_LIST_FILE}\"" )
endif()

set( INCLUDE_DIRS
src
)

set( PRIVATE_HEADERS
src/_MulleObjCOSFoundation-import-private.h
src/_MulleObjCOSFoundation-include-private.h
src/import-private.h
src/include-private.h
)

set( PUBLIC_HEADERS
src/MulleObjCLoader+MulleObjCOSFoundation.h
src/MulleObjCOSFoundation.h
src/_MulleObjCOSFoundation-import.h
src/_MulleObjCOSFoundation-include.h
src/import.h
src/include.h
src/objc-loader.inc
)

