# cmake/_Sources.cmake is generated by `mulle-sde`. Edits will be lost.
#
if( MULLE_TRACE_INCLUDE)
   MESSAGE( STATUS "# Include \"${CMAKE_CURRENT_LIST_FILE}\"" )
endif()

set( SOURCES
Functions/NSLog.m
Functions/mulle_posix_tm.c
MulleObjCPOSIXError.m
MulleObjCPOSIXString.m
NSBundle+Posix.m
NSCalendarDate+Posix.m
NSCondition.m
NSData+Posix.m
NSDate+Posix.m
NSDirectoryEnumerator+Posix.m
NSFileHandle+Posix.m
NSFileManager+Posix.m
NSLocale+Posix.m
NSPipe+Posix.m
_NSPosixDateFormatter.m
NSProcessInfo+Posix.m
NSRunLoop+Posix.m
NSTask+Posix.m
NSTimeZone+Posix.m
Timezone/localtime.c
)

set( STAGE2_SOURCES
MulleObjCLoader+MulleObjCPosixFoundation.m
)
