/*
   This file will be regenerated by `mulle-sde update|monitor`.
   Edits will be lost.
*/

#ifndef _mulleobjcosbasefoundation__dependencies_h__
#define _mulleobjcosbasefoundation__dependencies_h__

# include <MulleObjCInetFoundation/MulleObjCInetFoundation.h>   // MulleObjCInetFoundation

#endif
