/*
*   This file will be regenerated by `mulle-sde update` and any edits will be
*   lost. Suppress generation of this file with:
*      mulle-sde environment --global \
*         set MULLE_SOURCETREE_TO_C_IMPORT_FILE DISABLE
*
*   To not generate any header files:
*      mulle-sde environment --global \
*         set MULLE_SOURCETREE_TO_C_RUN DISABLE
*/

#ifndef _mulle_objc_os_base_foundation_import_h__
#define _mulle_objc_os_base_foundation_import_h__

// How to tweak the following MulleObjCStandardFoundation #import
//    remove:          `mulle-sourcetree mark MulleObjCStandardFoundation no-header`
//    rename:          `mulle-sourcetree mark MulleObjCStandardFoundation set include whatever.h`
//    toggle public:   `mulle-sourcetree mark MulleObjCStandardFoundation [no-]public`
//    toggle optional: `mulle-sourcetree mark MulleObjCStandardFoundation [no-]require`
//    remove for os:   `mulle-sourcetree mark MulleObjCStandardFoundation no-os-<osname>`
# import <MulleObjCStandardFoundation/MulleObjCStandardFoundation.h>   // MulleObjCStandardFoundation

#include "_MulleObjCOSBaseFoundation-include.h"


#endif
