      { @selector( MulleObjCLoader), @selector( MulleObjCInetFoundation) },      // 58bd58d3;MulleObjCLoader;307411f3;MulleObjCInetFoundation
      { @selector( MulleObjCLoader), @selector( MulleObjCStandardFoundation) },      // 58bd58d3;MulleObjCLoader;efe3d73e;MulleObjCStandardFoundation
      { @selector( NSArchiver), @selector( OSBase) },      // 3140e86c;NSArchiver;ec55440c;OSBase
      { @selector( NSArray), @selector( OSBasePrivate) },      // 55e6335f;NSArray;2d902ee5;OSBasePrivate
      { @selector( NSArray), @selector( Posix) },      // 55e6335f;NSArray;1ac23aba;Posix
      { @selector( NSBundle), MULLE_OBJC_NO_CATEGORYID },      // 301a6dd8;NSBundle;;
      { @selector( NSCalendarDate), @selector( NSUserDefaults) },      // 732630c6;NSCalendarDate;0944b917;NSUserDefaults
      { @selector( NSConditionLock), MULLE_OBJC_NO_CATEGORYID },      // 340900d6;NSConditionLock;;
      { @selector( NSData), @selector( OSBase) },      // 7d1455e8;NSData;ec55440c;OSBase
      { @selector( NSDate), @selector( NSUserDefaults) },      // 7d1455ec;NSDate;0944b917;NSUserDefaults
      { @selector( NSDictionary), @selector( OSBase) },      // ca46313c;NSDictionary;ec55440c;OSBase
      { @selector( NSDictionary), @selector( OSBasePrivate) },      // ca46313c;NSDictionary;2d902ee5;OSBasePrivate
      { @selector( NSDirectoryEnumerator), MULLE_OBJC_NO_CATEGORYID },      // 4609f60f;NSDirectoryEnumerator;;
      { @selector( NSFileHandle), @selector( NSRunLoop) },      // e82be8e0;NSFileHandle;68c55409;NSRunLoop
      { @selector( NSFileHandle), @selector( _NSFileDescriptor) },      // e82be8e0;NSFileHandle;946746f0;_NSFileDescriptor
      { @selector( NSFileHandle), MULLE_OBJC_NO_CATEGORYID },      // e82be8e0;NSFileHandle;;
      { @selector( NSFileManager), MULLE_OBJC_NO_CATEGORYID },      // be98ed67;NSFileManager;;
      { @selector( NSHost), @selector( OSBase) },      // 324806f6;NSHost;ec55440c;OSBase
      { @selector( NSNullDeviceFileHandle), MULLE_OBJC_NO_CATEGORYID },      // 9747f3d1;NSNullDeviceFileHandle;;
      { @selector( NSPipe), MULLE_OBJC_NO_CATEGORYID },      // 06832e24;NSPipe;;
      { @selector( NSProcessInfo), MULLE_OBJC_NO_CATEGORYID },      // f87f34cf;NSProcessInfo;;
      { @selector( NSRunLoop), MULLE_OBJC_NO_CATEGORYID },      // 68c55409;NSRunLoop;;
      { @selector( NSString), @selector( CString) },      // 85e3fa43;NSString;6eddb6b7;CString
      { @selector( NSString), @selector( OSBase) },      // 85e3fa43;NSString;ec55440c;OSBase
      { @selector( NSTask), @selector( System) },      // b04725e7;NSTask;8bce35aa;System
      { @selector( NSTask), MULLE_OBJC_NO_CATEGORYID },      // b04725e7;NSTask;;
      { @selector( NSURL), @selector( OSBase) },      // b15f7adb;NSURL;ec55440c;OSBase
      { @selector( NSUserDefaults), @selector( Conveniences) },      // 0944b917;NSUserDefaults;7fd11f11;Conveniences
      { @selector( NSUserDefaults), MULLE_OBJC_NO_CATEGORYID },      // 0944b917;NSUserDefaults;;
      { @selector( _NSPathUtilityVectorTable_Loader), MULLE_OBJC_NO_CATEGORYID },      // 9806676b;_NSPathUtilityVectorTable_Loader;;
