//
//  MulleObjCLoader+OSBase.m
//  MulleObjCOSFoundation
//
//  Created by Nat! on 11.05.17.
//  Copyright © 2017 Mulle kybernetiK. All rights reserved.
//

#import "MulleObjCOSFoundationParents.h"


@implementation MulleObjCLoader( MulleObjCOSBaseFoundation)

+ (struct _mulle_objc_dependency *) dependencies
{
   /*
      dependencies.inc are generated by:
      `${PROJECT_DIR}/make-osbase-dependencies.sh`
    */

   static struct _mulle_objc_dependency   dependencies[] =
   {
      { @selector( MulleObjCLoader), @selector( MulleObjCInetFoundation) },

#include "osbase-dependencies.inc"

      { MULLE_OBJC_NO_CLASSID, MULLE_OBJC_NO_CATEGORYID }
   };

   return( dependencies);
}

@end
