      { @selector( NSArchiver), @selector( OSBase) },      // 2a2e712f;NSArchiver;b8ece9a7;OSBase
      { @selector( NSArray), @selector( OSBase_Private) },      // 233490fe;NSArray;7cf4cba6;OSBase_Private
      { @selector( NSArray), @selector( Posix) },      // 233490fe;NSArray;ae1faa81;Posix
      { @selector( NSBundle), MULLE_OBJC_NO_CATEGORYID },      // c2f95c66;NSBundle;;
      { @selector( NSCalendarDate), @selector( NSUserDefaults) },      // b8742fcb;NSCalendarDate;272481b3;NSUserDefaults
      { @selector( NSConditionLock), MULLE_OBJC_NO_CATEGORYID },      // 5e0deecf;NSConditionLock;;
      { @selector( NSData), @selector( OSBase) },      // 8fce7861;NSData;b8ece9a7;OSBase
      { @selector( NSDate), @selector( NSUserDefaults) },      // cfcedd21;NSDate;272481b3;NSUserDefaults
      { @selector( NSDictionary), @selector( OSBase) },      // 8b2abcad;NSDictionary;b8ece9a7;OSBase
      { @selector( NSDictionary), @selector( OSBase_Private) },      // 8b2abcad;NSDictionary;7cf4cba6;OSBase_Private
      { @selector( NSDirectoryEnumerator), MULLE_OBJC_NO_CATEGORYID },      // c1158d70;NSDirectoryEnumerator;;
      { @selector( NSFileHandle), @selector( NSRunLoop) },      // 01a8a865;NSFileHandle;e3bb595b;NSRunLoop
      { @selector( NSFileHandle), @selector( _NSFileDescriptor) },      // 01a8a865;NSFileHandle;ec5a3bee;_NSFileDescriptor
      { @selector( NSFileHandle), MULLE_OBJC_NO_CATEGORYID },      // 01a8a865;NSFileHandle;;
      { @selector( NSFileManager), MULLE_OBJC_NO_CATEGORYID },      // 56d57ffc;NSFileManager;;
      { @selector( NSHost), @selector( OSBase) },      // fe455508;NSHost;b8ece9a7;OSBase
      { @selector( NSNullDeviceFileHandle), MULLE_OBJC_NO_CATEGORYID },      // 1a0784d4;NSNullDeviceFileHandle;;
      { @selector( NSPipe), MULLE_OBJC_NO_CATEGORYID },      // 09f46823;NSPipe;;
      { @selector( NSProcessInfo), MULLE_OBJC_NO_CATEGORYID },      // 208b1df5;NSProcessInfo;;
      { @selector( NSRunLoop), MULLE_OBJC_NO_CATEGORYID },      // e3bb595b;NSRunLoop;;
      { @selector( NSString), @selector( CString) },      // 1994a171;NSString;cafc9ab8;CString
      { @selector( NSString), @selector( OSBase) },      // 1994a171;NSString;b8ece9a7;OSBase
      { @selector( NSTask), @selector( System) },      // 90ec29ba;NSTask;f3184bc8;System
      { @selector( NSTask), MULLE_OBJC_NO_CATEGORYID },      // 90ec29ba;NSTask;;
      { @selector( NSURL), @selector( OSBase) },      // 6b1e8f73;NSURL;b8ece9a7;OSBase
      { @selector( NSUserDefaults), @selector( Conveniences) },      // 272481b3;NSUserDefaults;1d30cd9c;Conveniences
      { @selector( NSUserDefaults), MULLE_OBJC_NO_CATEGORYID },      // 272481b3;NSUserDefaults;;
      { @selector( _NSPathUtilityVectorTable_Loader), MULLE_OBJC_NO_CATEGORYID },      // ad89cd30;_NSPathUtilityVectorTable_Loader;;
