      { @selector( NSArchiver), @selector( OSBase) },   // 3140e86c,ec55440c
      { @selector( NSArray), @selector( OSBasePrivate) },   // 55e6335f,2d902ee5
      { @selector( NSCalendarDate), @selector( NSUserDefaults) },   // 732630c6,0944b917
      { @selector( NSDate), @selector( NSUserDefaults) },   // 7d1455ec,0944b917
      { @selector( NSData), @selector( OSBase) },   // 7d1455e8,ec55440c
      { @selector( NSDictionary), @selector( OSBase) },   // ca46313c,ec55440c
      { @selector( NSDictionary), @selector( OSBasePrivate) },   // ca46313c,2d902ee5
      { @selector( NSHost), @selector( OSBase) },   // 324806f6,ec55440c
      { @selector( NSString), @selector( CString) },   // 85e3fa43,6eddb6b7
      { @selector( NSString), @selector( OSBase) },   // 85e3fa43,ec55440c
      { @selector( NSTask), @selector( System) },   // b04725e7,8bce35aa
      { @selector( NSURL), @selector( OSBase) },   // b15f7adb,ec55440c
      { @selector( NSBundle), MULLE_OBJC_NO_CATEGORYID },   // 301a6dd8,00000000
      { @selector( NSConditionLock), MULLE_OBJC_NO_CATEGORYID },   // 340900d6,00000000
      { @selector( NSDirectoryEnumerator), MULLE_OBJC_NO_CATEGORYID },   // 4609f60f,00000000
      { @selector( NSFileHandle), @selector( _NSFileDescriptor) },   // e82be8e0,946746f0
      { @selector( NSFileHandle), @selector( NSRunLoop) },   // e82be8e0,68c55409
      { @selector( NSNullDeviceFileHandle), MULLE_OBJC_NO_CATEGORYID },   // 9747f3d1,00000000
      { @selector( NSFileHandle), MULLE_OBJC_NO_CATEGORYID },   // e82be8e0,00000000
      { @selector( NSFileManager), MULLE_OBJC_NO_CATEGORYID },   // be98ed67,00000000
      { @selector( NSPipe), MULLE_OBJC_NO_CATEGORYID },   // 06832e24,00000000
      { @selector( NSProcessInfo), MULLE_OBJC_NO_CATEGORYID },   // f87f34cf,00000000
      { @selector( NSRunLoop), MULLE_OBJC_NO_CATEGORYID },   // 68c55409,00000000
      { @selector( NSTask), MULLE_OBJC_NO_CATEGORYID },   // b04725e7,00000000
      { @selector( NSUserDefaults), MULLE_OBJC_NO_CATEGORYID },   // 0944b917,00000000
      { @selector( NSUserDefaults), @selector( Conveniences) },   // 0944b917,7fd11f11
      { @selector( _NSPosixDateFormatter), MULLE_OBJC_NO_CATEGORYID },   // 963fbdc8,00000000
