#
# cmake/_Sources.cmake is generated by `mulle-sde`. Edits will be lost.
#
if( MULLE_TRACE_INCLUDE)
   MESSAGE( STATUS "# Include \"${CMAKE_CURRENT_LIST_FILE}\"" )
endif()

set( SOURCES
NSBundle+Darwin.m
NSDateFormatter+Darwin.m
NSFileManager+Darwin.m
NSPathUtilities+Darwin.m
NSProcessInfo+Darwin.m
NSString+Darwin.m
NSTask+Darwin.m
)

set( STAGE2_SOURCES
MulleObjCLoader+MulleObjCDarwinFoundation.m
)
