/*
   This file will be regenerated by `mulle-sde update|monitor`.
   Edits will be lost.
*/

#ifndef _mulleobjcdarwinfoundation__dependencies_h__
#define _mulleobjcdarwinfoundation__dependencies_h__

# include <MulleObjCPosixFoundation/MulleObjCPosixFoundation.h>   // MulleObjCPosixFoundation

#endif
