      { @selector( MulleObjCLoader), @selector( MulleObjCBSDFoundation) },      // 58bd58d3;MulleObjCLoader;578a7a2a;MulleObjCBSDFoundation
      { @selector( NSBundle), @selector( Darwin) },      // 301a6dd8;NSBundle;5729b300;Darwin
      { @selector( NSFileManager), @selector( Darwin) },      // be98ed67;NSFileManager;5729b300;Darwin
      { @selector( NSProcessInfo), @selector( Darwin) },      // f87f34cf;NSProcessInfo;5729b300;Darwin
      { @selector( NSString), @selector( Darwin) },      // 85e3fa43;NSString;5729b300;Darwin
      { @selector( NSTask), @selector( Darwin) },      // b04725e7;NSTask;5729b300;Darwin
      { @selector( _NSPathUtilityVectorTable_Loader), @selector( Darwin) },      // 9806676b;_NSPathUtilityVectorTable_Loader;5729b300;Darwin
