      { @selector( MulleObjCLoader), @selector( MulleObjCBSDFoundation) },      // 47a9beb6;MulleObjCLoader;205c6909;MulleObjCBSDFoundation
      { @selector( NSBundle), @selector( Darwin) },      // c2f95c66;NSBundle;6d352c2f;Darwin
      { @selector( NSDateFormatter), @selector( Darwin) },      // 6d2cd542;NSDateFormatter;6d352c2f;Darwin
      { @selector( NSFileManager), @selector( Darwin) },      // 56d57ffc;NSFileManager;6d352c2f;Darwin
      { @selector( NSProcessInfo), @selector( Darwin) },      // 208b1df5;NSProcessInfo;6d352c2f;Darwin
      { @selector( NSString), @selector( Darwin) },      // 1994a171;NSString;6d352c2f;Darwin
      { @selector( NSTask), @selector( Darwin) },      // 90ec29ba;NSTask;6d352c2f;Darwin
      { @selector( _NSPathUtilityVectorTable_Loader), @selector( Darwin) },      // ad89cd30;_NSPathUtilityVectorTable_Loader;6d352c2f;Darwin
